# Backend Go (Staging)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # Image akan di-update secara otomatis oleh GitHub Actions saat deploy
        image: ghcr.io/khensin166/jadisah-backend:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres-staging-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "jadisah"
        - name: DB_NAME
          value: "jadisah_staging"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: staging-secret
              key: POSTGRES_PASSWORD
        - name: GIN_MODE
          value: "debug"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: backend
