all:
  children:
    k3s_servers:
      hosts:
        k8s-master-01:
          ansible_host: 100.79.211.49
          k3s_node_ip: 100.79.211.49
          # Private IP untuk SSH dan komunikasi ansible jika diperlukan
          # namun untuk Kubernetes node IP kita paksa menggunakan k3s_node_ip (Tailscale)

    k3s_workers:
      hosts: {}
      # Contoh penambahan ke depannya:
      # k8s-worker-01:
      #   ansible_host: 100.79.x.x
      #   k3s_node_ip: 100.79.x.x

    database:
      hosts: {}
